export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILURE = 'USER_DETAILS_FAILURE';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAILURE = 'USER_UPDATE_PROFILE_FAILURE';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_ADMIN_USER_LIST_REQUEST = 'USER_ADMIN_USER_LIST_REQUEST';
export const USER_ADMIN_USER_LIST_SUCCESS = 'USER_ADMIN_USER_LIST_SUCCESS';
export const USER_ADMIN_USER_LIST_FAILURE = 'USER_ADMIN_USER_LIST_FAILURE';
export const USER_ADMIN_USER_LIST_RESET = 'USER_ADMIN_USER_LIST_RESET';

export const USER_ADMIN_DELETE_USER_REQUEST = 'USER_ADMIN_DELETE_USER_REQUEST';
export const USER_ADMIN_DELETE_USER_SUCCESS = 'USER_ADMIN_DELETE_USER_SUCCESS';
export const USER_ADMIN_DELETE_USER_FAILURE = 'USER_ADMIN_DELETE_USER_FAILURE';

export const USER_ADMIN_UPDATE_USER_REQUEST = 'USER_ADMIN_UPDATE_USER_REQUEST';
export const USER_ADMIN_UPDATE_USER_SUCCESS = 'USER_ADMIN_UPDATE_USER_SUCCESS';
export const USER_ADMIN_UPDATE_USER_FAILURE = 'USER_ADMIN_UPDATE_USER_FAILURE';
export const USER_ADMIN_UPDATE_USER_RESET = 'USER_ADMIN_UPDATE_USER_RESET';

export const USER_ADD_TO_WISHLIST_REQUEST = 'USER_ADD_TO_WISHLIST_REQUEST';
export const USER_ADD_TO_WISHLIST_SUCCESS = 'USER_ADD_TO_WISHLIST_SUCCESS';
export const USER_ADD_TO_WISHLIST_FAILURE = 'USER_ADD_TO_WISHLIST_FAILURE';

export const USER_DELETE_WISHLIST_REQUEST = 'USER_DELETE_WISHLIST_REQUEST';
export const USER_DELETE_WISHLIST_SUCCESS = 'USER_DELETE_WISHLIST_SUCCESS';
export const USER_DELETE_WISHLIST_FAILURE = 'USER_DELETE_WISHLIST_FAILURE';

export const USER_WISHLIST_REQUEST = 'USER_WISHLIST_REQUEST';
export const USER_WISHLIST_SUCCESS = 'USER_WISHLIST_SUCCESS';
export const USER_WISHLIST_FAILURE = 'USER_WISHLIST_FAILURE';
export const USER_WISHLIST_RESET = 'USER_WISHLIST_RESET';
